# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-03 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170719_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isbanner',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u8f2a\u64ad'),
        ),
    ]
